"""empty message

Revision ID: ed32d31fb9a9
Revises: 5241e58c6824
Create Date: 2021-04-29 19:28:38.535856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed32d31fb9a9'
down_revision = '5241e58c6824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('updated_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'updated_date')
    # ### end Alembic commands ###
